#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
config=$DIR/config

linkdevs=`grep "^overc.network.linkdevs =" $config |cut -c 25-`

if [ -z "$linkdevs" ] ; then
    exit 0
fi

for dev in `(cd /sys/class/net && ls -dr $linkdevs 2>/dev/null)`; do
    echo lxc.network.type = phys >> $config
    echo lxc.network.link = $dev >> $config
done
