---
  - name: set system id
    command: /etc/overc-conf/system/systemid-set.sh

  - name: disable configure_network_prime in next boot
    replace:
      dest: /etc/overc-conf/ansible/overc_config_vars.yml
      regexp: '^configure_network_prime: true'
      replace: '#configure_network_prime: true'
