#!/bin/bash

function parse_conf_file() {
	# Read tuples from the config file in form a:b
	while read line; do
		a=$( echo $line|cut -d':' -f 1 )
		b=$( echo $line|cut -d':' -f 2 )
		case "$a" in
		shutdown)
			SHUTDOWN_ACTION="$b"
			;;
		reboot)
			REBOOT_ACTION="$b"
			;;
		monitor-container)
			container_to_monitor="$b"
			;;
		*)
			echo "Unknown $a:$b in ${CONF_FILE}"
			;;
		esac

	# Describing the input:
	# First take any lines containing a :
	# Throw away any of those that start with # (with optional leading whitespace)
	# Then compress out any whitespace surrounding any :

	done < <( grep ":" ${CONF_FILE} | grep -v ^[[:space:]]*# | sed s/[[:space:]]*:[[:space:]]*/:/g )
		
}

##############  Mainline begins here ################################

CONF_FILE=/etc/cube-cmd-server.conf
container_to_monitor="none"

. /etc/cube-cmd-server-functions

parse_conf_file

if [ "${container_to_monitor}" == "none" ]; then
	echo "No container to monitor"
	exit 2
fi

setup_listening_mechanism fifo

while (true) do
	read line

	case "${line}" in
	poweroff)
		case "${SHUTDOWN_ACTION}" in
		ignore)
			;;
		shutdown)
			shutdown -h now
			;;
		*)
			echo "Unknown shutdown action ${SHUTDOWN_ACTION}, ignoring"
			;;
		esac
		;;
	reboot)
		case "${REBOOT_ACTION}" in
		ignore)
			;;
		reboot)
			reboot
			;;
		*)
			echo "Unknown reboot action ${REBOOT_ACTION}, ignoring"
			;;
		esac
		;;
	esac
done <${listening_mechanism_input_stream}
