#!/bin/bash

. /etc/cube-cmd-server-functions

container_to_monitor="local"

setup_sending_mechanism fifo ${container_to_monitor}

target_state=$( systemctl list-units --type=target )
echo ${target_state} | grep -qi reboot
if [ $? == 0 ]; then
	command="reboot"
else
	echo ${target_state} | grep -qi poweroff
	if [ $? == 0 ]; then
		command="poweroff"
	fi
fi

whoami=`cat /etc/hostname`

timeout 5s bash -c "echo ${command}:${whoami} >${sending_mechanism_output_stream}"
