#!/bin/bash

#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License version 2 as
#  published by the Free Software Foundation.

#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#  See the GNU General Public License for more details.

BASEDIR=$(dirname $BASH_SOURCE)

usage()
{
cat << EOF

   ${0##*/} <command> <args>

  example:
    
EOF
}

if [ -z "$1" ]; then
    usage
    exit
fi

command=$1

while [ $# -gt 0 ]; do
    case "$1" in
	-v) verbose=t
	    verbose_flag="-v"
            ;;
        *) break
            ;;
    esac
    shift
done

PATH=${PATH}:${BASEDIR}

case ${command} in
    ctl)
	# yank the "ctl" off
	shift
	c3-ctl $@
	;;
    console)
	# yank the "console" off
	shift
	c3-console $@
	;;
    cmd)
	shift
	c3-cmd $@
	;;
    cfg)
	shift
	c3-cfg ${verbose_flag} $@
	;;
    search)
	shift
	for d in bin containers layers lib repos; do
	    mkdir -p ~/.udocker/${d}
	done
	udocker --allow-root search "$@"
	;;
    *)
	# front cube-ctl by default
	c3-ctl ${verbose_flag} $@
	;;
esac
