#!/bin/bash

# TODO: move to a simple init system, like docker's tiny-init, since we will
#       miss some reaping / exiting capabilities with this
if [ "$1" == "start" ] || [ -z "$1" ]; then
    # Ensure we have some prerequisites in place
    mkdir -p /var/run/openvswitch

    /usr/bin/dnsmasq -x /run/dnsmasq.pid -7 /etc/dnsmasq.d --local-service --resolv-file=/etc/vrf-resolv.conf

    # We can't exit else the container will be destroyed
    sleep infinity
fi

if [ "$1" == "restart" ]; then
    dnspid=$(cat /var/run/dnsmasq.pid)
    if [ -n "${dnspid}" ]; then
	kill -9 ${dnspid}
    fi

    /usr/bin/dnsmasq -x /run/dnsmasq.pid -7 /etc/dnsmasq.d --local-service --resolv-file=/etc/vrf-resolv.conf
fi
