#!/bin/bash
#
# Copyright (C) 2015 Wind River Systems, Inc.
#

function updatepkg_info()
{
    CNList="$1"

    UpdateFlag=0
    touch /etc/motd
    grep -v '^CUBEUPDATE: ' /etc/motd > /tmp/$$.motd
    
    echo "CUBEUPDATE: " >> /tmp/$$.motd
    echo "CUBEUPDATE: update packages information on `date`" > /etc/cube-update/network.log
    for cn in $CNList; do
        RET=`system_newer.sh $cn | tail -n 1`
	if [ X"$RET" == X"-1" ]; then
            echo "CUBEUPDATE: WARNING: The $cn networks is unreachable" >> /tmp/$$.motd
	elif [ $RET -gt 0 ]; then
            echo "CUBEUPDATE: NOTICE: The $cn has updates available" >> /tmp/$$.motd
            echo "CUBEUPDATE: NOTICE: The $cn has $RET new packages available" >> /tmp/$$.motd
            UpdateFlag=1
        else
            echo "CUBEUPDATE: NOTICE: The $cn has no upgrades available" >> /tmp/$$.motd
        fi
        if [ X"$cn" != X"essential" -a X"$cn" != X"dom0" ]; then
            SYSContainerName=$cn
        fi
    done

    if [ $UpdateFlag -eq 1 ]; then
        echo "CUBEUPDATE: " >> /tmp/$$.motd
        echo "CUBEUPDATE: Please login to dom0 to execute system upgrade command:" >> /tmp/$$.motd
        echo "CUBEUPDATE: /opt/overc-system-agent/overc system upgrade dom0 -r" >> /tmp/$$.motd
        echo "CUBEUPDATE: After all container upgrades are completed, the system will reboot to the upgraded version." >> /tmp/$$.motd
    fi
    echo "CUBEUPDATE: " >> /tmp/$$.motd
    mv /tmp/$$.motd /etc/motd

    if [ -n "$SYSContainerName" ]; then
        grep -v '^CUBEUPDATE: ' /opt/container/$SYSContainerName/rootfs/etc/motd > /tmp/$SYSContainerName.motd
        grep '^CUBEUPDATE: ' /etc/motd >> /tmp/$SYSContainerName.motd
        mv /tmp/$SYSContainerName.motd /opt/container/$SYSContainerName/rootfs/etc/motd
    fi
}

updatepkg_info "$1"
