#!/bin/sh

LAYERS="meta-openembedded \
	meta-virtualization \
	meta-overc \
	"
	 
if [ ! -d meta-overc ]; then
	echo I do not see a meta-overc subdir.  Are you in poky dir\?
	exit 1
fi

echo Updating main repo
git pull || exit 1

for i in $LAYERS
do
	if [ ! -d "$i" ]; then
		echo Layer $i does not appear to exist.  Giving up.
		exit 1
	fi
	cd $i || exit 1
	echo Updating layer $i
	git pull
	if [ $? != 0 ]; then
		echo git pull in layer $i failed.  Giving up.
		exit 1
	fi
	cd - > /dev/null
done
